import { Term } from './term';

export const TERMS: Term[] = [
    { term: "あ", meanings: ["a"]},
    { term: "い", meanings: ["i"]},
    { term: "う", meanings: ["u"]},
    { term: "え", meanings: ["e"]},
    { term: "お", meanings: ["o"]},
    { term: "か", meanings: ["ka"]},
    { term: "き", meanings: ["ki"]},
    { term: "く", meanings: ["ku"]},
    { term: "け", meanings: ["ke"]},
    { term: "こ", meanings: ["ko"]},
    { term: "さ", meanings: ["sa"]},
    { term: "し", meanings: ["shi"]},
    { term: "す", meanings: ["su"]},
    { term: "せ", meanings: ["se"]},
    { term: "そ", meanings: ["so"]},
    { term: "た", meanings: ["ta"]},
    { term: "ち", meanings: ["chi"]},
    { term: "つ", meanings: ["tsu"]},
    { term: "て", meanings: ["te"]},
    { term: "と", meanings: ["to"]},
    { term: "な", meanings: ["na"]},
    { term: "に", meanings: ["ni"]},
    { term: "ぬ", meanings: ["nu"]},
    { term: "ね", meanings: ["ne"]},
    { term: "の", meanings: ["no"]},
    { term: "は", meanings: ["ha"]},
    { term: "ひ", meanings: ["hi"]},
    { term: "ふ", meanings: ["fu"]},
    { term: "へ", meanings: ["he"]},
    { term: "ほ", meanings: ["ho"]},
    { term: "ま", meanings: ["ma"]},
    { term: "み", meanings: ["mi"]},
    { term: "む", meanings: ["mu"]},
    { term: "め", meanings: ["me"]},
    { term: "も", meanings: ["mo"]},
    { term: "や", meanings: ["ya"]},
    { term: "ゆ", meanings: ["yu"]},
    { term: "よ", meanings: ["yo"]},
    { term: "ら", meanings: ["ra"]},
    { term: "り", meanings: ["ri"]},
    { term: "る", meanings: ["ru"]},
    { term: "れ", meanings: ["re"]},
    { term: "ろ", meanings: ["ro"]},
    { term: "わ", meanings: ["wa"]},
    { term: "を", meanings: ["wo", "o"]},
    { term: "ん", meanings: ["n"]}
];